#Request root permissions to the TravisCI runtime environment
sudo: required
#Tell TravisCI that we're using docker to run our tests
services:
    - docker
#Build our test Docker container
before_install:
  - docker build -t wjwmichael/vue-portfolio -f Dockerfile.test .

#Run our test Docker container
script:
  - docker run wjwmichael/vue-portfolio

#Build our deployment container
before_deploy:
  - docker build -t wjwmichael/vue-portfolio .

#Run our deployment container via shell script if commiting to the master branch
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master